# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            "PHPackaton 2014"
tagline:          "Hackathon for PHP developers"
url:              "http://phpers.github.io/phpackaton"
paginate:         1
baseurl:          "http://phpers.github.io/phpackaton"
author:
  name:           "Michał Łukaszewski"
  url:            "http://michal.lukaszewski.eu"
  email:          "mlukaszewski@gmail.com"

# Custom vars
version:          1.0.0
github:
  repo:           "https://github.com/PHPers/phpackaton"
