# Dependencies
markdown:         redcarpet
highlighter: pygments
markdown:    kramdown

# Permalinks
permalink:        pretty

# Setup
title:            "PHPackaton 2014"
tagline:          "Hackathon for PHP developers"
url:              "http://phpers.github.io/phpackaton/"
paginate:         1
baseurl:          "http://phpers.github.io/phpackaton/"
author:
  name:           "Michał Łukaszewski"
  url:            "http://michal.lukaszewski.eu"
  email:          "mlukaszewski@gmail.com"
  


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# Custom vars
version:          1.0.0
github:
  repo:           "https://github.com/PHPers/phpackaton/"
